pipeline {
    agent {
        label 'iaccess-builder'
    }

    stages {
        stage('Build') {
            steps {
                sh './build.sh'
            }
        }
    }

    post {
        always {
            // Clean after build
            cleanWs()
        }
    }
}
